version: "3.9"

services:
  football_api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
        - .:/usr/football_bot_api
    command: >
      sh -c "poetry run python football_service/manage.py wait_for_db &&
             poetry run python football_service/manage.py migrate &&
             poetry run python football_service/manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=notifier_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=notifier_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - ./data:/var/lib/postgresql/data