version: "3.9"

services:
  football_api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
        - .:/usr/football-bot-api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=notifier_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword