version: "3.9"

services:
  football_api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
        - .:/usr/football-bot-api
    environment:
      - DB_HOST=db
      - DB_NAME=notifier_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword