---
name: Checks

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker-compose run --rm football_api sh -c "python -m black --check ." &&
             docker-compose run --rm football_api sh -c "python -m isort --check-only ." &&
             docker-compose run --rm football_telegram_bot sh -c "python -m flake8 --max-line-length=120" .


